# Generated by Django 4.2.1 on 2023-08-31 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App2', '0007_remove_product_category_order_order_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.PositiveIntegerField(default='', unique=True),
        ),
    ]
