# Generated by Django 4.2.1 on 2023-08-31 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App2', '0011_alter_order_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
    ]
