# Generated by Django 4.2.1 on 2023-08-31 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App2', '0012_remove_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.IntegerField(default=1),
        ),
    ]
