# Generated by Django 4.2.4 on 2023-08-31 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App2', '0015_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
